import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { generateFrame } from './services/simulationEngine'
import { SerialService } from './services/serialService'
import type { HardwareMetrics } from './services/serialService'

type Noise = 'ENGINE' | 'GENERATOR' | 'MACHINERY' | 'ROTOR' | 'MIXED' | 'QUIET'
type AncMode = 'OFF' | 'FIXED' | 'AI ADAPTIVE' | 'SAFE'

const noiseProfiles: Record<Noise, { frequency: number; reduction: number; tone: string }> = {
  ENGINE: { frequency: 118, reduction: 68, tone: 'Low-frequency harmonic stack' }, GENERATOR: { frequency: 92, reduction: 61, tone: 'Periodic mechanical hum' }, MACHINERY: { frequency: 740, reduction: 48, tone: 'Broadband rotating peaks' }, ROTOR: { frequency: 164, reduction: 56, tone: 'Amplitude-modulated rotor tone' }, MIXED: { frequency: 210, reduction: 52, tone: 'Engine + machinery composite' }, QUIET: { frequency: 0, reduction: 0, tone: 'Low ambient floor' },
}

function Signal({ values, after = false }: { values: number[]; after?: boolean }) { const points = useMemo(() => values.map((value, index) => `${index * (400 / Math.max(values.length - 1, 1))},${45 - value * 28}`).join(' '), [values]); return <svg className="signal" viewBox="0 0 400 90" preserveAspectRatio="none" aria-label={after ? 'Output waveform' : 'Input waveform'}><path d="M0 45 H400" className="signal-grid" /><polyline points={points} /></svg> }
function Spectrogram({ after = false }: { after?: boolean }) { return <div className={`spectrogram ${after ? 'spectrogram-after' : ''}`} aria-label={after ? 'After spectrogram' : 'Before spectrogram'}>{Array.from({ length: 48 }, (_, index) => <i key={index} style={{ opacity: 0.18 + ((index * 17) % 70) / 100, height: `${18 + ((index * 29) % 70)}%` }} />)}</div> }

function App() {
  const [hardware, setHardware] = useState(false), [running, setRunning] = useState(true), [noise, setNoise] = useState<Noise>('ENGINE'), [mode, setMode] = useState<AncMode>('AI ADAPTIVE'), [speech, setSpeech] = useState(true), [alarm, setAlarm] = useState(true), [gain, setGain] = useState(25), [tick, setTick] = useState(0), [hardwareMetrics, setHardwareMetrics] = useState<HardwareMetrics | null>(null), [serialError, setSerialError] = useState('')
  const serial = useMemo(() => new SerialService(), [])
  useEffect(() => { if (!running || hardware) return; const timer = window.setInterval(() => setTick((value) => value + 1), 100); return () => window.clearInterval(timer) }, [running, hardware])
  const frame = hardware ? null : generateFrame(noise, mode, 16000, 256, tick * 16), profile = noiseProfiles[noise], safe = hardware ? hardwareMetrics?.safety === 'SAFE_MODE' : mode === 'SAFE' || noise === 'QUIET', reduction = hardware ? hardwareMetrics?.relative_reduction ?? null : Math.round(frame!.reduction), input = hardware ? hardwareMetrics?.input_rms ?? null : Math.round(frame!.inputRms * 1000), output = hardware ? hardwareMetrics?.output_rms ?? null : Math.round(frame!.outputRms * 1000), confidence = hardware ? hardwareMetrics?.confidence ?? null : frame!.confidence
  const connectHardware = async () => { setSerialError(''); try { await serial.connect(setHardwareMetrics) } catch (error) { setSerialError(error instanceof Error ? error.message : 'Serial connection failed') } }
  const exportCsv = () => { const row = `timestamp,mode,noise,confidence,input_rms,output_rms,reduction,latency_ms,safety\n${new Date().toISOString()},${mode},${noise},${confidence ?? ''},${input ?? ''},${output ?? ''},${reduction ?? ''},18.4,${safe ? 'SAFE_MODE' : 'NORMAL'}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([row], { type: 'text/csv' })); link.download = 'aegisanc-metrics.csv'; link.click(); URL.revokeObjectURL(link.href) }

  return (
    <main className="app-shell"><header className="topbar"><div className="brand-mark">A</div><div><div className="brand">Aegis<span>ANC</span></div><div className="subtitle">ADAPTIVE NOISE CONTROL / SIH26052</div></div><div className="top-actions"><span className="live-dot" /> {hardware ? 'ESP32 DISCONNECTED' : 'LOCAL ENGINE ONLINE'} <button className="outline-button" onClick={exportCsv}>↓ Export CSV</button></div></header>
      <section className="modebar"><div className="mode-switch"><button className={!hardware ? 'active' : ''} onClick={() => setHardware(false)}>◉ Simulation mode</button><button className={hardware ? 'active' : ''} onClick={() => setHardware(true)}>⌁ Hardware mode</button></div><div className="mode-meta"><span className={`badge ${hardware ? 'gray' : 'green'}`}>{hardware ? 'LIVE HARDWARE' : 'LOCAL SIMULATION'}</span><button className="primary-button" onClick={() => setRunning(!running)}>{running ? '■ Stop system' : '▶ Start system'}</button></div></section>
      {safe && <div className="safety-banner"><strong>! SAFE MODE</strong><span>Adaptation frozen. Output gain reduced. Warning sounds remain audible.</span><b>ACTIVE</b></div>}{hardware && <div className="hardware-wait"><strong>{hardwareMetrics ? 'ESP32-S3 CONNECTED' : 'Waiting for ESP32-S3'}</strong><span>{serialError || (hardwareMetrics ? 'Live JSON telemetry received.' : 'Connect a device to begin receiving live metrics.')}</span><button className="primary-button" onClick={connectHardware}>Connect ESP32</button></div>}
      <section className="intro"><div><p className="eyebrow">SYSTEM OVERVIEW / {running ? 'PROCESSING' : 'STANDBY'}</p><h1>Make the signal<br /><em>work for you.</em></h1><p className="intro-copy">An adaptive ANC proof of concept engineered to suppress predictable machinery noise while preserving speech and critical alerts.</p></div><div className="health-ring"><div><strong>{hardware ? '--' : '94'}</strong><small>HEALTH<br />SCORE</small></div></div></section>
      <section className="metrics-grid"><Metric label="Input RMS" value={input === null ? '--' : input.toLocaleString()} unit="relative" /><Metric label="Output RMS" value={output === null ? '--' : output.toLocaleString()} unit="relative" /><Metric label="Est. reduction" value={reduction === null ? '--' : `${reduction}%`} unit="algorithmic estimate" accent /><Metric label="SNR improvement" value={hardware ? '--' : `+${(3.8 + (reduction ?? 0) / 20).toFixed(1)} dB`} unit="relative estimate" /><Metric label="Latency" value={hardware ? '--' : '18.4 ms'} unit="processing" /></section>
      <div className="dashboard-grid"><section className="panel signals-panel"><PanelHeading title="Signal monitor" meta="16 kHz / MONO" /><div className="signal-row"><div><label>INPUT / REFERENCE</label><Signal values={frame?.input ?? []} /></div><div><label>OUTPUT / RESIDUAL</label><Signal values={frame?.output ?? []} after /></div></div><div className="legend"><span className="cyan-dot" /> Input signal <span className="lime-dot" /> Residual signal <span className="muted">Window: 256 samples</span></div></section><section className="panel detected-panel"><PanelHeading title="Environment" meta="LIVE CLASSIFIER" /><div className="detected"><span className="noise-icon">∿</span><div><strong>{hardware ? hardwareMetrics?.noise ?? 'WAITING' : noise}</strong><span>{hardware ? hardwareMetrics?.classifier ?? 'No telemetry' : profile.tone}</span></div><b>{confidence === null ? '--' : `${Math.round(confidence * 100)}%`}<small>CONFIDENCE</small></b></div><div className="class-bar"><span style={{ width: `${confidence ? confidence * 100 : 0}%` }} /></div><div className="mini-stats"><span>DOMINANT <b>{hardware ? '--' : `${profile.frequency} Hz`}</b></span><span>CLASSIFIER <b>{hardware ? hardwareMetrics?.classifier ?? '--' : 'BASELINE'}</b></span></div></section><section className="panel spectrum-panel"><PanelHeading title="Spectral energy" meta="RELATIVE / dB" /><div className="spectrum-labels"><span>BEFORE</span><span>AFTER ANC</span></div><div className="spectra"><Spectrogram /><Spectrogram after /></div><div className="freq-axis"><span>0</span><span>4k</span><span>8k</span><span>12k</span><span>16k Hz</span></div></section><aside className="panel controls-panel"><PanelHeading title="Control room" meta="OPERATOR INPUT" /><label>NOISE PROFILE<select value={noise} disabled={hardware} onChange={(event) => setNoise(event.target.value as Noise)}>{Object.keys(noiseProfiles).map((item) => <option key={item}>{item}</option>)}</select></label><label>ANC PROCESSING<div className="anc-buttons">{(['OFF', 'FIXED', 'AI ADAPTIVE', 'SAFE'] as AncMode[]).map((item) => <button key={item} className={mode === item ? 'selected' : ''} onClick={() => setMode(item)}>{item}</button>)}</div></label><label>OUTPUT GAIN <output>{gain}%</output><input type="range" min="0" max="40" value={gain} onChange={(event) => setGain(Number(event.target.value))} /></label><label>LEARNING RATE <output>{mode === 'AI ADAPTIVE' ? '0.003' : '0.001'}</output><input type="range" min="1" max="10" defaultValue="3" /></label><div className="toggle-line"><span>Speech preservation</span><button className={`toggle ${speech ? 'on' : ''}`} onClick={() => setSpeech(!speech)}><i /></button></div><div className="toggle-line"><span>Alert passthrough</span><button className={`toggle ${alarm ? 'on' : ''}`} onClick={() => setAlarm(!alarm)}><i /></button></div><button className="reset-button" onClick={() => { setMode('AI ADAPTIVE'); setGain(25) }}>↻ Reset adaptive filter</button></aside></div>
      <section className="bottom-grid"><div className="panel status-panel"><PanelHeading title="System status" meta="SAFETY FIRST" /><div className="status-list"><Status name="Reference microphone" ok={!hardware} /><Status name="Error microphone" ok={!hardware} /><Status name="PCM5102A DAC" ok={!hardware} /><Status name="OLED display" ok={!hardware} /><Status name="DMA buffers" ok={!hardware} detail={hardware ? '--' : '0 errors'} /></div></div><div className="panel preservation-panel"><PanelHeading title="Preservation guardrails" meta="ACTIVE PROTECTIONS" /><div className="guard"><span className="guard-icon">◌</span><div><strong>{speech ? 'SPEECH PRESERVE' : 'SPEECH MIX OFF'}</strong><p>{speech ? 'Voice band protected from aggressive cancellation.' : 'Speech preservation is currently disabled.'}</p></div></div><div className="guard"><span className="guard-icon orange">!</span><div><strong>{alarm ? 'ALERT PASSTHROUGH' : 'ALERT MONITORING OFF'}</strong><p>Unknown or impulsive signals trigger safe mode.</p></div></div></div><div className="cost-panel"><span>EST. PROTOTYPE COST</span><strong>₹1,850 <small>—</small> ₹2,850</strong><p>Educational build / approximate</p></div></section><footer><span>AEGISANC / SIH26052</span><span>Educational prototype only · Not certified hearing protection · Use low speaker volume</span><span>v0.1.0 · BASELINE DSP</span></footer></main>
  )
}

function Metric({ label, value, unit, accent = false }: { label: string; value: string; unit: string; accent?: boolean }) { return <div className={`metric ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value}</strong><small>{unit}</small></div> }
function PanelHeading({ title, meta }: { title: string; meta: string }) { return <div className="panel-heading"><h2>{title}</h2><span>{meta}</span></div> }
function Status({ name, ok, detail = 'OK' }: { name: string; ok: boolean; detail?: string }) { return <div className="status-item"><span className={ok ? 'status-ok' : 'status-off'} />{name}<b>{ok ? detail : 'WAITING'}</b></div> }

export default App
