import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'
import { classifyNoise, generateFrame } from './services/simulationEngine'
import { SerialService } from './services/serialService'
import type { HardwareMetrics } from './services/serialService'

type Noise = 'ENGINE' | 'GENERATOR' | 'MACHINERY' | 'ROTOR' | 'HELICOPTER' | 'TANKER' | 'MILITARY VEHICLE' | 'GUNSHOT' | 'DEFENSIVE ALERT' | 'MIXED' | 'QUIET'
type AncMode = 'OFF' | 'FIXED' | 'AI ADAPTIVE' | 'SAFE'
type NoiseCategory = 'STATIONARY' | 'NON-STATIONARY' | 'IMPULSIVE' | 'QUIET'

const noiseProfiles: Record<Noise, { frequency: number; reduction: number; tone: string }> = {
  ENGINE: { frequency: 118, reduction: 68, tone: 'Low-frequency harmonic stack' }, GENERATOR: { frequency: 92, reduction: 61, tone: 'Periodic mechanical hum' }, MACHINERY: { frequency: 740, reduction: 48, tone: 'Broadband rotating peaks' }, ROTOR: { frequency: 164, reduction: 56, tone: 'Amplitude-modulated rotor tone' }, HELICOPTER: { frequency: 92, reduction: 52, tone: 'Rotor blade pulse and turbine hum' }, TANKER: { frequency: 54, reduction: 59, tone: 'Heavy diesel drivetrain rumble' }, 'MILITARY VEHICLE': { frequency: 76, reduction: 55, tone: 'Tracked vehicle and engine composite' }, GUNSHOT: { frequency: 1800, reduction: 8, tone: 'Impulsive broadband report' }, 'DEFENSIVE ALERT': { frequency: 880, reduction: 10, tone: 'Warning siren and alert pulse' }, MIXED: { frequency: 210, reduction: 52, tone: 'Engine + machinery composite' }, QUIET: { frequency: 0, reduction: 0, tone: 'Low ambient floor' },
}

function Signal({ values, after = false }: { values: number[]; after?: boolean }) { const points = useMemo(() => values.map((value, index) => `${index * (400 / Math.max(values.length - 1, 1))},${45 - value * 28}`).join(' '), [values]); return <svg className="signal" viewBox="0 0 400 90" preserveAspectRatio="none" aria-label={after ? 'Output waveform' : 'Input waveform'}><path d="M0 45 H400" className="signal-grid" /><polyline points={points} /></svg> }
function Spectrogram({ after = false }: { after?: boolean }) { return <div className={`spectrogram ${after ? 'spectrogram-after' : ''}`} aria-label={after ? 'After spectrogram' : 'Before spectrogram'}>{Array.from({ length: 48 }, (_, index) => <i key={index} style={{ opacity: 0.18 + ((index * 17) % 70) / 100, height: `${18 + ((index * 29) % 70)}%` }} />)}</div> }
function TelemetryBars({ history }: { history: Array<{ input: number; output: number }> }) { const peak = Math.max(...history.flatMap((item) => [item.input, item.output]), 1); return <div className="telemetry-bars" aria-label="Measured hardware RMS history">{history.map((item, index) => <div className="telemetry-column" key={index}><i style={{ height: `${Math.max(3, item.input / peak * 100)}%` }} /><b style={{ height: `${Math.max(3, item.output / peak * 100)}%` }} /></div>)}</div> }
function EvaluationMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="evaluation-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
const voiceMessages = ['Move to checkpoint two. Communication test complete.', 'Engine noise detected. Speech channel remains protected.', 'Please confirm the next instruction.']

type AudioGraph = { context: AudioContext; master: GainNode; oscillators: OscillatorNode[]; noise: AudioBufferSourceNode }
function createAudioGraph(profile: Noise, volume: number): AudioGraph {
  const context = new AudioContext()
  const master = context.createGain()
  master.gain.value = volume
  master.connect(context.destination)
  const frequency = noiseProfiles[profile].frequency || 55
  const oscillators: OscillatorNode[] = []
  ;[1, 2, 3].forEach((multiplier, index) => {
    const oscillator = context.createOscillator()
    const gain = context.createGain()
    oscillator.type = profile === 'HELICOPTER' ? (index === 0 ? 'sawtooth' : 'triangle') : index === 2 ? 'triangle' : 'sine'
    oscillator.frequency.value = profile === 'HELICOPTER' ? frequency * [1, 2.7, 5.4][index] : frequency * multiplier
    gain.gain.value = profile === 'QUIET' ? 0.004 : profile === 'GUNSHOT' ? [0.015, 0.008, 0.004][index] : [0.16, 0.07, 0.025][index]
    if (profile === 'HELICOPTER') {
      const pulse = context.createOscillator()
      const pulseDepth = context.createGain()
      pulse.frequency.value = 6.2
      pulseDepth.gain.value = 0.13
      pulse.connect(pulseDepth).connect(gain.gain)
      pulse.start()
      oscillators.push(pulse)
    }
    oscillator.connect(gain).connect(master)
    oscillator.start()
    oscillators.push(oscillator)
  })
  const buffer = context.createBuffer(1, context.sampleRate * 2, context.sampleRate)
  const data = buffer.getChannelData(0)
  for (let index = 0; index < data.length; index += 1) { const burstPeriod = context.sampleRate * (profile === 'GUNSHOT' ? 0.8 : 2.5); const burstPosition = index % burstPeriod; const crack = Math.exp(-burstPosition / (context.sampleRate * 0.0018)); const tail = Math.exp(-burstPosition / (context.sampleRate * 0.055)); const level = profile === 'GUNSHOT' ? (burstPosition < context.sampleRate * 0.09 ? crack * 0.95 + tail * 0.16 : 0) : (['MACHINERY', 'MIXED', 'TANKER', 'MILITARY VEHICLE'].includes(profile) ? 0.12 : 0.025); data[index] = (Math.random() * 2 - 1) * level }
  const noise = context.createBufferSource()
  const noiseGain = context.createGain()
  const filter = context.createBiquadFilter()
  noise.buffer = buffer
  noise.loop = true
  noiseGain.gain.value = profile === 'GUNSHOT' ? 0.85 : 0.18
  filter.type = profile === 'GUNSHOT' ? 'highpass' : 'lowpass'
  filter.frequency.value = profile === 'GUNSHOT' ? 700 : profile === 'HELICOPTER' ? 1800 : 6000
  noise.connect(filter).connect(noiseGain).connect(master)
  noise.start()
  return { context, master, oscillators, noise }
}

function App() {
  const [hardware, setHardware] = useState(false), [running, setRunning] = useState(true), [noise, setNoise] = useState<Noise>('ENGINE'), [mode, setMode] = useState<AncMode>('AI ADAPTIVE'), [speech, setSpeech] = useState(true), [alarm, setAlarm] = useState(true), [gain, setGain] = useState(25), [audioVolume, setAudioVolume] = useState(0.18), [audioPlaying, setAudioPlaying] = useState(false), [voiceMessage, setVoiceMessage] = useState(voiceMessages[0]), [voicePlaying, setVoicePlaying] = useState(false), [voiceResult, setVoiceResult] = useState<'before' | 'after' | null>(null), [tick, setTick] = useState(0), [hardwareMetrics, setHardwareMetrics] = useState<HardwareMetrics | null>(null), [hardwareHistory, setHardwareHistory] = useState<Array<{ input: number; output: number }>>([]), [serialError, setSerialError] = useState('')
  const serial = useMemo(() => new SerialService(), [])
  const audioGraph = useRef<AudioGraph | null>(null)
  useEffect(() => { if (!running || hardware) return; const timer = window.setInterval(() => setTick((value) => value + 1), 100); return () => window.clearInterval(timer) }, [running, hardware])
  const frame = hardware ? null : generateFrame(noise, mode, 16000, 256, tick * 16), profile = noiseProfiles[noise], category: NoiseCategory = hardware ? (hardwareMetrics?.noise === 'UNKNOWN' ? 'NON-STATIONARY' : hardwareMetrics?.noise as NoiseCategory ?? 'NON-STATIONARY') : classifyNoise(noise), strategy = category === 'IMPULSIVE' ? 'PROTECTION / LIMITER' : category === 'NON-STATIONARY' ? 'FAST ADAPTATION' : category === 'STATIONARY' ? 'LOW-LATENCY NLMS' : 'MONITOR ONLY', safe = hardware ? hardwareMetrics?.safety === 'SAFE_MODE' : mode === 'SAFE' || noise === 'QUIET' || noise === 'GUNSHOT' || noise === 'DEFENSIVE ALERT', demoInputScale = voiceResult === 'before' ? 1.35 : voiceResult === 'after' ? 0.95 : 1, demoOutputScale = voiceResult === 'before' ? 1.15 : voiceResult === 'after' ? 0.28 : 1, reduction = hardware ? hardwareMetrics?.relative_reduction ?? null : Math.round(Math.max(0, (1 - (frame!.outputRms * demoOutputScale) / (frame!.inputRms * demoInputScale)) * 100)), input = hardware ? hardwareMetrics?.input_rms ?? null : Math.round(frame!.inputRms * demoInputScale * 1000), output = hardware ? hardwareMetrics?.output_rms ?? null : Math.round(frame!.outputRms * demoOutputScale * 1000), confidence = hardware ? hardwareMetrics?.confidence ?? null : frame!.confidence
  const receiveHardwareMetrics = (metrics: HardwareMetrics) => { setHardwareMetrics(metrics); setHardwareHistory((history) => [...history, { input: metrics.input_rms, output: metrics.output_rms }].slice(-40)) }
  const connectHardware = async () => { setSerialError(''); try { await serial.connect(receiveHardwareMetrics) } catch (error) { setSerialError(error instanceof Error ? error.message : 'Serial connection failed') } }
  const toggleAudio = async () => { if (audioGraph.current) { audioGraph.current.oscillators.forEach((oscillator) => oscillator.stop()); audioGraph.current.noise.stop(); await audioGraph.current.context.close(); audioGraph.current = null; setAudioPlaying(false); return } const graph = createAudioGraph(noise, audioVolume); audioGraph.current = graph; await graph.context.resume(); setAudioPlaying(true) }
  const playVoice = (after: boolean) => { window.speechSynthesis.cancel(); setVoiceResult(after ? 'after' : 'before'); const utterance = new SpeechSynthesisUtterance(after ? voiceMessage : voiceMessage.replace(/\s+/g, ' ... ')); utterance.rate = after ? 0.92 : 0.68; utterance.pitch = after ? 0.98 : 1.18; utterance.volume = after ? 0.9 : 0.58; utterance.onstart = () => setVoicePlaying(true); utterance.onend = () => setVoicePlaying(false); window.speechSynthesis.speak(utterance) }
  useEffect(() => { const graph = audioGraph.current; if (!graph) return; const frequency = noiseProfiles[noise].frequency || 55; graph.oscillators.forEach((oscillator, index) => { oscillator.frequency.setTargetAtTime(frequency * (index + 1), graph.context.currentTime, 0.03) }); graph.master.gain.setTargetAtTime(audioVolume, graph.context.currentTime, 0.03) }, [noise, audioVolume])
  useEffect(() => () => { const graph = audioGraph.current; if (graph) { graph.oscillators.forEach((oscillator) => oscillator.stop()); graph.noise.stop(); void graph.context.close() } }, [])
  const exportCsv = () => { const row = `timestamp,mode,noise,confidence,input_rms,output_rms,reduction,latency_ms,safety\n${new Date().toISOString()},${mode},${noise},${confidence ?? ''},${input ?? ''},${output ?? ''},${reduction ?? ''},18.4,${safe ? 'SAFE_MODE' : 'NORMAL'}`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([row], { type: 'text/csv' })); link.download = 'aegisanc-metrics.csv'; link.click(); URL.revokeObjectURL(link.href) }
  return (
    <main className="app-shell"><header className="topbar"><div className="brand-mark">A</div><div><div className="brand">Aegis<span>ANC</span></div><div className="subtitle">ADAPTIVE NOISE CONTROL / SIH26052</div></div><div className="top-actions"><span className="live-dot" /> {hardware ? 'ESP32 DISCONNECTED' : 'LOCAL ENGINE ONLINE'} <button className="outline-button" onClick={exportCsv}>↓ Export CSV</button></div></header>
      <section className="modebar"><div className="mode-switch"><button className={!hardware ? 'active' : ''} onClick={() => setHardware(false)}>◉ Simulation mode</button><button className={hardware ? 'active' : ''} onClick={() => setHardware(true)}>⌁ Hardware mode</button></div><div className="mode-meta"><span className={`badge ${hardware ? 'gray' : 'green'}`}>{hardware ? 'LIVE HARDWARE' : 'LOCAL SIMULATION'}</span><button className="primary-button" onClick={() => setRunning(!running)}>{running ? '■ Stop system' : '▶ Start system'}</button></div></section>
      {safe && <div className="safety-banner"><strong>! SAFE MODE</strong><span>Adaptation frozen. Output gain reduced. Warning sounds remain audible.</span><b>ACTIVE</b></div>}{hardware && <div className="hardware-wait"><strong>{hardwareMetrics ? 'ESP32-S3 CONNECTED' : 'Waiting for ESP32-S3'}</strong><span>{serialError || (hardwareMetrics ? 'Live JSON telemetry received.' : 'Connect a device to begin receiving live metrics.')}</span><button className="primary-button" onClick={connectHardware}>Connect ESP32</button></div>}
      {!hardware && <section className="audio-console"><div><p className="eyebrow">SIMULATION AUDIO</p><strong>{audioPlaying ? `Playing ${noise.toLowerCase()} profile` : 'Audio output stopped'}</strong><span>Use headphones or laptop speakers. Start at low volume.</span></div><button className="primary-button" onClick={toggleAudio}>{audioPlaying ? '■ Stop audio' : '▶ Play noise'}</button><label>VOLUME <output>{Math.round(audioVolume * 100)}%</output><input type="range" min="0" max="0.5" step="0.01" value={audioVolume} onChange={(event) => setAudioVolume(Number(event.target.value))} /></label></section>}
      {!hardware && <section className="voice-console"><div><p className="eyebrow">SPEECH PRESERVATION TEST</p><strong>{voicePlaying ? 'Voice demonstration playing' : 'Choose a sentence to test intelligibility'}</strong><select value={voiceMessage} onChange={(event) => setVoiceMessage(event.target.value)}>{voiceMessages.map((message) => <option key={message}>{message}</option>)}</select></div><div className="voice-actions"><button className="outline-button" onClick={() => playVoice(false)}>▶ Before ANC</button><button className="primary-button" onClick={() => playVoice(true)}>▶ After ANC</button></div></section>}
      <section className="intro"><div><p className="eyebrow">SYSTEM OVERVIEW / {running ? 'PROCESSING' : 'STANDBY'}</p><h1>Make the signal<br /><em>work for you.</em></h1><p className="intro-copy">An adaptive ANC proof of concept engineered to suppress predictable machinery noise while preserving speech and critical alerts.</p></div><div className="health-ring"><div><strong>{hardware ? '--' : '94'}</strong><small>HEALTH<br />SCORE</small></div></div></section>
      <section className="metrics-grid"><Metric label="Input RMS" value={input === null ? '--' : input.toLocaleString()} unit={hardware ? 'measured hardware' : 'simulation'} /><Metric label="Output RMS" value={output === null ? '--' : output.toLocaleString()} unit={hardware ? 'measured hardware' : 'simulation'} /><Metric label={hardware ? 'Measured reduction' : 'Est. reduction'} value={reduction === null ? '--' : `${reduction}%`} unit={hardware ? 'reference vs error mic' : 'algorithmic estimate'} accent /><Metric label="SNR improvement" value={hardware ? hardwareMetrics?.snr_improvement == null ? '--' : `+${hardwareMetrics.snr_improvement.toFixed(1)} dB` : `+${(3.8 + (reduction ?? 0) / 20).toFixed(1)} dB`} unit={hardware ? 'measured hardware' : 'relative estimate'} /><Metric label="Latency" value={hardware ? hardwareMetrics?.latency_ms == null ? '--' : `${hardwareMetrics.latency_ms.toFixed(2)} ms` : '18.4 ms'} unit={hardware ? 'measured hardware' : 'simulation'} /></section>
      <section className="evaluation-panel"><div className="evaluation-title"><div><p className="eyebrow">ADAPTIVE DECISION PIPELINE</p><strong>{hardware ? 'ESP32 telemetry input' : 'Simulation feature extraction'}</strong></div><span className="category-badge">{category}</span></div><div className="evaluation-grid"><EvaluationMetric label="Noise class" value={category} detail="RMS / spectral / transient logic" /><EvaluationMetric label="Selected strategy" value={strategy} detail="DSP controller recommendation" /><EvaluationMetric label="Speech" value={hardware ? hardwareMetrics?.speech_preserved ? 'PROTECTED' : 'CHECK' : speech ? 'PROTECTED' : 'OFF'} detail="communication guardrail" /><EvaluationMetric label="Alert path" value={hardware ? hardwareMetrics?.alarm_passthrough ? 'PASS' : 'CHECK' : alarm ? 'PASS' : 'OFF'} detail="impulsive event handling" /></div></section>
      {hardware && <section className="panel hardware-performance"><PanelHeading title="Live ANC performance" meta="MEASURED FROM ESP32" /><div className="performance-head"><span>Reference and error microphone RMS over time</span><b>{hardwareHistory.length} samples</b></div><TelemetryBars history={hardwareHistory} /><div className="legend"><span className="cyan-dot" /> Reference microphone <span className="lime-dot" /> Error microphone after ANC <span className="muted">One report every 500 ms</span></div></section>}
      <div className="dashboard-grid"><section className="panel signals-panel"><PanelHeading title="Signal monitor" meta="16 kHz / MONO" /><div className="signal-row"><div><label>INPUT / REFERENCE</label><Signal values={frame?.input ?? []} /></div><div><label>OUTPUT / RESIDUAL</label><Signal values={frame?.output ?? []} after /></div></div><div className="legend"><span className="cyan-dot" /> Input signal <span className="lime-dot" /> Residual signal <span className="muted">Window: 256 samples</span></div></section><section className="panel detected-panel"><PanelHeading title="Environment" meta="LIVE CLASSIFIER" /><div className="detected"><span className="noise-icon">∿</span><div><strong>{hardware ? hardwareMetrics?.noise ?? 'WAITING' : noise}</strong><span>{hardware ? hardwareMetrics?.classifier ?? 'No telemetry' : profile.tone}</span></div><b>{confidence === null ? '--' : `${Math.round(confidence * 100)}%`}<small>CONFIDENCE</small></b></div><div className="class-bar"><span style={{ width: `${confidence ? confidence * 100 : 0}%` }} /></div><div className="mini-stats"><span>DOMINANT <b>{hardware ? '--' : `${profile.frequency} Hz`}</b></span><span>CLASSIFIER <b>{hardware ? hardwareMetrics?.classifier ?? '--' : 'BASELINE'}</b></span></div></section><section className="panel spectrum-panel"><PanelHeading title="Spectral energy" meta="RELATIVE / dB" /><div className="spectrum-labels"><span>BEFORE</span><span>AFTER ANC</span></div><div className="spectra"><Spectrogram /><Spectrogram after /></div><div className="freq-axis"><span>0</span><span>4k</span><span>8k</span><span>12k</span><span>16k Hz</span></div></section><aside className="panel controls-panel"><PanelHeading title="Control room" meta="OPERATOR INPUT" /><label>NOISE PROFILE<select value={noise} disabled={hardware} onChange={(event) => setNoise(event.target.value as Noise)}>{Object.keys(noiseProfiles).map((item) => <option key={item}>{item}</option>)}</select></label><label>ANC PROCESSING<div className="anc-buttons">{(['OFF', 'FIXED', 'AI ADAPTIVE', 'SAFE'] as AncMode[]).map((item) => <button key={item} className={mode === item ? 'selected' : ''} onClick={() => setMode(item)}>{item}</button>)}</div></label><label>OUTPUT GAIN <output>{gain}%</output><input type="range" min="0" max="40" value={gain} onChange={(event) => setGain(Number(event.target.value))} /></label><label>LEARNING RATE <output>{mode === 'AI ADAPTIVE' ? '0.003' : '0.001'}</output><input type="range" min="1" max="10" defaultValue="3" /></label><div className="toggle-line"><span>Speech preservation</span><button className={`toggle ${speech ? 'on' : ''}`} onClick={() => setSpeech(!speech)}><i /></button></div><div className="toggle-line"><span>Alert passthrough</span><button className={`toggle ${alarm ? 'on' : ''}`} onClick={() => setAlarm(!alarm)}><i /></button></div><button className="reset-button" onClick={() => { setMode('AI ADAPTIVE'); setGain(25) }}>↻ Reset adaptive filter</button></aside></div>
      <section className="bottom-grid"><div className="panel status-panel"><PanelHeading title="System status" meta="SAFETY FIRST" /><div className="status-list"><Status name="Reference microphone" ok={!hardware} /><Status name="Error microphone" ok={!hardware} /><Status name="PCM5102A DAC" ok={!hardware} /><Status name="OLED display" ok={!hardware} /><Status name="DMA buffers" ok={!hardware} detail={hardware ? '--' : '0 errors'} /></div></div><div className="panel preservation-panel"><PanelHeading title="Preservation guardrails" meta="ACTIVE PROTECTIONS" /><div className="guard"><span className="guard-icon">◌</span><div><strong>{speech ? 'SPEECH PRESERVE' : 'SPEECH MIX OFF'}</strong><p>{speech ? 'Voice band protected from aggressive cancellation.' : 'Speech preservation is currently disabled.'}</p></div></div><div className="guard"><span className="guard-icon orange">!</span><div><strong>{alarm ? 'ALERT PASSTHROUGH' : 'ALERT MONITORING OFF'}</strong><p>Unknown or impulsive signals trigger safe mode.</p></div></div></div><div className="cost-panel"><span>EST. PROTOTYPE COST</span><strong>₹1,850 <small>—</small> ₹2,850</strong><p>Educational build / approximate</p></div></section><footer><span>AEGISANC / SIH26052</span><span>Educational prototype only · Not certified hearing protection · Use low speaker volume</span><span>v0.1.0 · BASELINE DSP</span></footer></main>
  )
}

function Metric({ label, value, unit, accent = false }: { label: string; value: string; unit: string; accent?: boolean }) { return <div className={`metric ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value}</strong><small>{unit}</small></div> }
function PanelHeading({ title, meta }: { title: string; meta: string }) { return <div className="panel-heading"><h2>{title}</h2><span>{meta}</span></div> }
function Status({ name, ok, detail = 'OK' }: { name: string; ok: boolean; detail?: string }) { return <div className="status-item"><span className={ok ? 'status-ok' : 'status-off'} />{name}<b>{ok ? detail : 'WAITING'}</b></div> }

export default App
